# Generated by Django 5.1.9 on 2025-05-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('bio', models.CharField(max_length=1250)),
                ('birth', models.DateTimeField()),
                ('death', models.DateTimeField()),
                ('prof', models.CharField(max_length=35)),
                ('portrait', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=35)),
                ('passwd', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=1250)),
                ('publicationDate', models.DateTimeField()),
                ('genres', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('credential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.credential')),
                ('nick', models.CharField(max_length=35)),
                ('joinDate', models.DateTimeField()),
            ],
            bases=('core.credential',),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('publicationDate', models.DateTimeField()),
                ('publisher', models.CharField(max_length=70)),
                ('lang', models.CharField(max_length=10)),
                ('pages', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=70)),
                ('cover', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
    ]
