# Generated by Django 5.1.9 on 2025-05-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credential_ptr',
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
