# Generated by Django 5.1.9 on 2025-06-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_credential_ptr_delete_credential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='portrait',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='file',
            field=models.FileField(upload_to='books/'),
        ),
    ]
