# Generated by Django 5.1.9 on 2025-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_portrait_alter_edition_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='autor',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='edition',
            name='publicationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
