# Generated by Django 5.1.9 on 2025-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='readed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reading',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited', to='core.edition'),
        ),
        migrations.AddField(
            model_name='profile',
            name='readed',
            field=models.ManyToManyField(related_name='readed', to='core.edition'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reading',
            field=models.ManyToManyField(related_name='reading', to='core.edition'),
        ),
    ]
