# Generated by Django 5.1.9 on 2025-06-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_profile_favorites_remove_profile_readed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited', to='core.edition'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='readed',
            field=models.ManyToManyField(blank=True, related_name='readed', to='core.edition'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reading',
            field=models.ManyToManyField(blank=True, related_name='reading', to='core.edition'),
        ),
    ]
